version: '3'

services:
  blog:
    image: pojono/blog:latest
    container_name: blog
    restart: always
    networks:
      - web
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.backend=blog
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:pojono.com
      - traefik.port=80

networks:
  web:
    external:
      name: web
  default:
    driver: bridge
