version: '3'

services:
  blog:
    build: .
    image: jenkins:latest
    container_name: jenkins
    restart: always
    networks:
      - web
      - default
    expose:
      - 8080
    labels:
      - traefik.enable=true
      - traefik.backend=jenkins
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:jenkins.pojono.ru
      - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:

networks:
  web:
    external:
      name: web
  default:
    driver: bridge