version: '2'
services:
  minio:
    restart: always
    container_name: minio_s3
    image: minio/minio
    ports:
      - '9000:9000'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio125
    command: server /export
