name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag latest

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASS }}" | docker login -u ${{ secrets.DOCKER_REGISTRY_USER }} --password-stdin

      - name: Push image
        run:
            docker tag blog:latest pojono/blog:latest
            docker push pojono/blog:latest
